export interface Product {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  rating: number;
  reviewCount: number;
  stock: number;
  badges?: string[];
  features?: string[];
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "智慧藍牙耳機 Pro",
    nameEn: "Smart Bluetooth Earbuds Pro",
    description: "主動降噪、40小時續航、IPX5防水，支援多點連接。採用最新藍牙5.3技術，提供穩定的無線連接體驗。",
    descriptionEn: "Active noise cancellation, 40hr battery, IPX5 waterproof with multi-point connection. Latest Bluetooth 5.3 technology for stable wireless experience.",
    price: 2490,
    originalPrice: 3290,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400&h=400&fit=crop",
    category: "electronics",
    rating: 4.7,
    reviewCount: 1283,
    stock: 156,
    badges: ["熱銷"],
    features: ["主動降噪", "40小時續航", "IPX5防水", "藍牙5.3"],
  },
  {
    id: "p2",
    name: "極簡筆電支架",
    nameEn: "Minimalist Laptop Stand",
    description: "鋁合金材質，人體工學設計，支援11-17吋筆電。可摺疊收納，輕量攜帶。",
    descriptionEn: "Aluminum alloy, ergonomic design, supports 11-17 inch laptops. Foldable and lightweight for easy carry.",
    price: 890,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop",
    category: "electronics",
    rating: 4.5,
    reviewCount: 567,
    stock: 89,
    features: ["鋁合金", "人體工學", "可摺疊"],
  },
  {
    id: "p3",
    name: "機械鍵盤 TKL",
    nameEn: "Mechanical Keyboard TKL",
    description: "Cherry MX 紅軸，RGB背光，PBT鍵帽。87鍵緊湊設計，Type-C可拆卸線材。",
    descriptionEn: "Cherry MX Red switches, RGB backlight, PBT keycaps. 87-key compact design with detachable USB-C cable.",
    price: 3200,
    originalPrice: 3800,
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=400&fit=crop",
    category: "electronics",
    rating: 4.8,
    reviewCount: 892,
    stock: 43,
    badges: ["新品"],
    features: ["Cherry MX", "RGB背光", "PBT鍵帽", "Type-C"],
  },
  {
    id: "p4",
    name: "經典棉質T恤",
    nameEn: "Classic Cotton T-Shirt",
    description: "100%有機棉，舒適透氣，多色可選。寬鬆版型，適合日常穿搭。",
    descriptionEn: "100% organic cotton, breathable comfort, multiple colors. Relaxed fit for everyday wear.",
    price: 590,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop",
    category: "clothing",
    rating: 4.3,
    reviewCount: 2104,
    stock: 320,
    features: ["有機棉", "透氣", "寬鬆版型"],
  },
  {
    id: "p5",
    name: "戶外防風外套",
    nameEn: "Outdoor Windbreaker Jacket",
    description: "防風防水面料，可收納式設計，適合登山與城市通勤。反光條設計提升夜間安全。",
    descriptionEn: "Wind and water resistant, packable design for hiking and commuting. Reflective strips for night safety.",
    price: 1890,
    originalPrice: 2490,
    image: "https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=400&h=400&fit=crop",
    category: "clothing",
    rating: 4.6,
    reviewCount: 438,
    stock: 67,
    badges: ["熱銷"],
    features: ["防風防水", "可收納", "反光條"],
  },
  {
    id: "p6",
    name: "北歐風陶瓷花瓶",
    nameEn: "Nordic Ceramic Vase",
    description: "手工製作，啞光質感，適合乾燥花與鮮花擺設。極簡設計為居家增添優雅氣息。",
    descriptionEn: "Handcrafted matte finish, perfect for dried and fresh flowers. Minimalist design adds elegance to any space.",
    price: 680,
    image: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=400&h=400&fit=crop",
    category: "home",
    rating: 4.4,
    reviewCount: 213,
    stock: 45,
    features: ["手工製作", "啞光質感", "極簡設計"],
  },
  {
    id: "p7",
    name: "瑜珈墊 加厚版",
    nameEn: "Premium Yoga Mat - Extra Thick",
    description: "10mm加厚，環保TPE材質，雙面防滑。附贈收納帶，方便攜帶。",
    descriptionEn: "10mm thick, eco-friendly TPE material, double-sided non-slip. Includes carrying strap.",
    price: 980,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop",
    category: "sports",
    rating: 4.5,
    reviewCount: 756,
    stock: 132,
    features: ["10mm加厚", "環保TPE", "雙面防滑"],
  },
  {
    id: "p8",
    name: "程式設計入門指南",
    nameEn: "Programming Beginner's Guide",
    description: "從零開始學程式，涵蓋Python、JavaScript基礎。實戰案例教學，適合初學者。",
    descriptionEn: "Learn programming from scratch. Covers Python and JavaScript basics with hands-on projects for beginners.",
    price: 420,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop",
    category: "books",
    rating: 4.2,
    reviewCount: 389,
    stock: 200,
    badges: ["新品"],
    features: ["Python", "JavaScript", "實戰案例"],
  },
  {
    id: "p9",
    name: "智能手錶 S3",
    nameEn: "Smart Watch S3",
    description: "AMOLED螢幕，心率血氧監測，50m防水。支援NFC支付與GPS定位。",
    descriptionEn: "AMOLED display, heart rate & SpO2 monitoring, 50m water resistant. NFC payment and GPS supported.",
    price: 4590,
    originalPrice: 5990,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    category: "electronics",
    rating: 4.6,
    reviewCount: 1567,
    stock: 28,
    badges: ["熱銷"],
    features: ["AMOLED", "心率血氧", "NFC", "GPS"],
  },
  {
    id: "p10",
    name: "香氛蠟燭禮盒",
    nameEn: "Scented Candle Gift Set",
    description: "天然大豆蠟，四款香氛：薰衣草、白茶、雪松、海洋微風。精美禮盒包裝。",
    descriptionEn: "Natural soy wax, four scents: lavender, white tea, cedar, ocean breeze. Elegant gift box packaging.",
    price: 1280,
    image: "https://images.unsplash.com/photo-1602607544921-b9d7ca583234?w=400&h=400&fit=crop",
    category: "home",
    rating: 4.7,
    reviewCount: 634,
    stock: 78,
    badges: ["新品"],
    features: ["天然大豆蠟", "四款香氛", "禮盒包裝"],
  },
];

export const CATEGORIES = ["all", "electronics", "clothing", "home", "sports", "books"] as const;
export type Category = (typeof CATEGORIES)[number];
